
# To create the environment: conda env create -f environment.yml
# To activate the environment: conda activate yolov1_env


name: yolov1_env

channels:
  - pytorch      # Highest priority for PyTorch packages
  - conda-forge  # High priority for most other packages
  - defaults

dependencies:
  # Python and Core Libraries
  - python=3.11
  - pip>=25.0
  - jupyterlab   # Explicitly install JupyterLab
  - ipykernel

  # Pytorch
  - pytorch
  - torchvision
  - torchaudio

  # Data Science & Utility Libraries
  - matplotlib
  - pandas
  - pandas-datareader
  - pillow
  - pyyaml
  - requests
  - scipy
  - tqdm
  - libjpeg-turbo # significantly accelerates JPEG compression and decompression on various platforms (x86, x86-64, ARM, PowerPC, MIPS) by utilizing SIMD instructions.

  # Use pip only for packages not available on conda channels
  - pip: 
    # - example_package